cloud:
  aws:
    credentials:
      access-key: AKIA2IC7DSYTCNRHAUFQ
      secret-key: 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
    region:
      static: us-east-1
      auto: false
      use-default-aws-region-chain: true
    end-point:
      url: https://sqs.us-east-1.amazonaws.com/704574101030/alura-sqs
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error