cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-1
      auto: false
      use-default-aws-region-chain: true
    end-point:
      url: https://sqs.us-east-1.amazonaws.com/704574101030/alura-sqs
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error